tms_django/api/urls.py
from django.urls import include, path

app_name = "api"
urlpatterns = [
    path("v1/", include("api.v1.urls")),
    # TODO: add api-doc
]

tms_django/apps/tms/urls.py
from apps.tms import views
from django.urls import path

app_name = "tms"

urlpatterns = [
    path("", views.HomePageView.as_view(), name="home_page"),
    path("load/", views.BookedLoadCreateView.as_view(), name="load_create"),
    path("load/<int:pk>/", views.BookedLoadDetailView.as_view(), name="load_detail"),
    path("load/<int:pk>/update/", views.BookedLoadUpdateView.as_view(), name="load_update"),
    path("load/<int:pk>/delete/", views.BookedLoadDeleteView.as_view(), name="load_delete"),
    path("load/list/", views.booked_load_filtered, name="loadlist"),
]

tms_django/config/urls.py
from admin.manager_admin.admin import manager_admin_site
from admin.super_admin.admin import admin
from django.urls import include, path

urlpatterns = [
    # Admin
    path("admin_super/", admin.site.urls),
    path("admin_manager/", manager_admin_site.urls),
    # API
    path("api/", include("api.urls")),
    path("api/auth/", include("rest_framework.urls", namespace="rest_framework")),
    # APP
    path("tms/", include("apps.tms.urls")),
]

tms_django/tms_django/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

tms_django/apps/tms/models.py
from apps.tms.generators import generate_invoice_id, generate_load_id, generate_unit_id
from django.conf import settings
from django.core.validators import MinValueValidator
from django.db import OperationalError, models
from django.utils.translation import gettext_lazy as _
from loguru import logger


class TruckKind(models.TextChoices):
    SPRINTER = "sprinter"
    SMALL_STRAIGHT = "small_straight"
    LARGE_STRAIGHT = "large_straight"


class Truck(models.Model):
    kind = models.CharField(choices=TruckKind, max_length=255)
    weight = models.IntegerField(null=True, default=None, validators=[MinValueValidator(0)])
    capacity = models.IntegerField(null=True, default=None, validators=[MinValueValidator(0)])

    def __str__(self) -> str:
        return f"{self.kind} id={self.id}"


class DriverProfile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, related_name="driver_profile", on_delete=models.CASCADE)
    unit_id = models.CharField(max_length=6, unique=True, db_index=True, default=generate_unit_id)
    phone_number = models.CharField(max_length=255, blank=False)
    driver_licence = models.CharField(max_length=255, blank=False)
    date_of_birth = models.DateField(null=True, blank=False)
    address = models.CharField(max_length=255)
    truck = models.ForeignKey(Truck, null=True, on_delete=models.CASCADE)

    def __str__(self) -> str:
        return f"unit_id={self.unit_id}"


class DispatcherProfile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, related_name="dispatcher_profile", on_delete=models.CASCADE)
    phone_number = models.CharField(max_length=255)

    def __str__(self) -> str:
        return f"id={self.id}"


class Broker(models.Model):
    agent_name = models.CharField(max_length=50)
    company_name = models.CharField(max_length=50)
    mc_number = models.CharField(max_length=10)

    def __str__(self) -> str:
        return f"{self.agent_name} from {self.company_name}, id={self.id}"


class BookedLoad(models.Model):
    class Status(models.TextChoices):
        PENDING = "pending", _("PENDING")
        HEADING_TO_THE_PICKUP = "heading_to_the_pickup", _("HEADING_TO_THE_PICKUP")
        LOADING = "loading", _("LOADING")
        ON_ROUTE = "on_route", _("ON_ROUTE")
        UNLOADING = "unloading", _("UNLOADING")
        DELIVERED = "delivered", _("DELIVERED")
        INVOICED = "invoiced", _("INVOICED")
        CANCELLED = "cancelled", _("CANCELLED")
        COMPLETED = "completed", _("COMPLETED")
        VOIDED = "voided", _("VOIDED")

    load_id = models.CharField(max_length=6, unique=True, db_index=True, default=generate_load_id)
    status = models.CharField(choices=Status, max_length=255)
    driver = models.ForeignKey("tms.DriverProfile", on_delete=models.CASCADE)
    pickup_location = models.CharField(max_length=30)
    delivery_location = models.CharField(max_length=30)
    distance = models.IntegerField(null=True, default=None, validators=[MinValueValidator(0)])
    pallets_quantity = models.IntegerField(null=True, default=None, validators=[MinValueValidator(0)])
    pallets_weight = models.IntegerField(null=True, default=None, validators=[MinValueValidator(0)])
    dispatcher = models.ForeignKey("tms.DispatcherProfile", on_delete=models.CASCADE)
    broker = models.ForeignKey(Broker, on_delete=models.CASCADE)
    total_rate = models.IntegerField(default=None)
    driver_rate = models.IntegerField(default=None)
    invoice_id = models.CharField(max_length=8, unique=True, db_index=True, default=generate_invoice_id)

    def __str__(self) -> str:
        return f"load_id={self.load_id} [{self.status}]"


class Billing(BookedLoad):
    # TODO: move me to admin module
    class Meta:
        proxy = True
        verbose_name_plural = "Billing"

tms_django/apps/tms/views.py
import django_filters
from django.forms import ModelForm
from django.shortcuts import render
from django.urls import reverse, reverse_lazy
from django.views.generic import (
    CreateView,
    DeleteView,
    DetailView,
    ListView,
    TemplateView,
    UpdateView,
)

from .models import BookedLoad


class HomePageView(TemplateView):
    template_name = "home_page.html"


class BookedLoadCreateForm(ModelForm):
    class Meta:
        model = BookedLoad
        fields = [
            "status",
            "driver",
            "pickup_location",
            "delivery_location",
            "distance",
            "pallets_quantity",
            "pallets_weight",
            "dispatcher",
            "broker",
            "total_rate",
            "driver_rate",
        ]


class BookedLoadCreateView(CreateView):
    model = BookedLoad
    form_class = BookedLoadCreateForm
    template_name = "bookedload_create_form.html"

    def get_success_url(self):
        return reverse("tms:load_detail", kwargs={"pk": self.object.pk})


#
class BookedLoadDetailView(DetailView):
    model = BookedLoad
    template_name = "bookedload_detail.html"


class BookedLoadListView(ListView):
    model = BookedLoad
    template_name = "bookedload_list.html"
    context_object_name = "load_list"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        load_list = list(self.get_queryset().values())
        context["load_list"] = load_list
        return context


class BookedLoadUpdateView(UpdateView):
    model = BookedLoad
    fields = "__all__"
    template_name = "bookedload_update_form.html"
    success_url = reverse_lazy("tms:load_list")


class BookedLoadDeleteView(DeleteView):
    model = BookedLoad
    success_url = reverse_lazy("tms:load_list")


class BookedLoadFilter(django_filters.FilterSet):
    class Meta:
        model = BookedLoad
        fields = ["load_id", "status", "dispatcher", "broker"]


def booked_load_filtered(request):
    f = BookedLoadFilter(request.GET, queryset=BookedLoad.objects.all())
    return render(request, "bookedload_list.html", {"filter": f})

tms_django/apps/tms/templates/bookedload_confirm_delete.html
<h1>Are you sure you want to delete this load?</h1>


<form method="POST">
    {% csrf_token %}
    <input type="submit" value="Confirm Delete">

</form>

tms_django/apps/tms/templates/bookedload_create_form.html
<h1> Create new Load </h1>
<form method = "POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="CREATE">

</form>

tms_django/apps/tms/templates/bookedload_detail.html
<h1> Booked Load Information: </h1>
<p>Load id: {{ bookedload.load_id }}</p>
<p>Current status: {{ bookedload.status }}</p>
<p> Driver: {{ bookedload.driver }}</p>
<p>Pickup location: {{ bookedload.pickup_location }}</p>
<p>Delivery location: {{ bookedload.delivery_location }}</p>
<p>Distance: {{ bookedload.distance }}</p>
<p>Pallets quantity: {{ bookedload.pallets_quantity }}</p>
<p>Pallets weight: {{ bookedload.pallets_weight }}</p>
<p>Dispatcher: {{ bookedload.dispatcher }}</p>
<p>Broker info: {{ bookedload.broker }}</p>
<p>Total rate: {{ bookedload.total_rate }}</p>
<p>Driver rate: {{ bookedload.driver_rate }}</p>

tms_django/apps/tms/templates/bookedload_list.html
<h1>Booked loads:</h1>

<form method="get" action="{% url 'tms:loadlist' %}">
    {{ filter.form.as_p }}
    <button type="submit">Filter</button>
</form>

<ul>
    {% for bookedload in filter.qs %}
        {{ bookedload.driver }} {{ bookedload.pickup_location }} {{ bookedload.delivery_location }}

        <ul>
            <li>
                <a href="{% url 'tms:load_detail' bookedload.id %}">Detailed information</a>
            </li>

            <li>
                <a href="{% url 'tms:load_update' bookedload.id %}">UPDATE information</a>
            </li>

            <li>
                <a href="{% url 'tms:load_delete' bookedload.id %}">Delete</a>
            </li>
        </ul>
    {% endfor %}
</ul>

tms_django/apps/tms/templates/bookedload_update_form.html
<form method="post">{% csrf_token %}
    {{ bookedload }}
    {{ form.as_p }}

    <input type="submit" value="Update">
</form>

tms_django/apps/tms/templates/home_page.html
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</head>
<body>
<h1>HOMEPAGE</h1>

<ul class="nav">
  <li class="nav-item">
    <a class="nav-link active" aria-current="page" href={% url "apps:tms:load_create" %}>Create Load</a>

    <li class="nav-item">
    <a class="nav-link" href={% url "apps:tms:loadlist" %}>Load List </a>
  </li>


</ul>

</body>
</html>